version: "3.1"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: agrc
      POSTGRES_USER: agrc
      POSTGRES_DB: opensgid
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./tests/data/pgdata.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    image: masquerade
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      PORT: 5000
    volumes:
      - ./cert.pem:/app/certs/cert.pem
      - ./key.pem:/app/certs/key.pem
      - ./.env:/app/.env

volumes:
  db:
