name: Issue Events

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    name: Create Reminder
    runs-on: ubuntu-latest

    steps:
      - name: check for reminder
        uses: agrc/create-reminder-action@v1
