name: Push Events

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: write
  id-token: write
  deployments: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

    steps:
      - name: 🚀 Create Release
        id: release-please
        uses: agrc/release-composite-action@v1
        with:
          release-type: python
          prerelease: ${{ github.ref_name == 'dev' }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          github-app-id: ${{ secrets.UGRC_RELEASE_BOT_APP_ID }}
          github-app-key: ${{ secrets.UGRC_RELEASE_BOT_APP_KEY }}
          github-app-name: ${{ secrets.UGRC_RELEASE_BOT_NAME }}
          github-app-email: ${{ secrets.UGRC_RELEASE_BOT_EMAIL }}

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: release
    environment:
      name: dev
    if: github.ref_name == 'dev' && needs.release.outputs.release_created

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🚢 Deploy
        uses: ./github/actions/deploy
        with:
          web-api-key: ${{ secrets.WEB_API_KEY }}
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          deploy-flags: |
            --cpu=1
            --memory=128Mi
            --min-instances=0
            --max-instances=5
            --timeout=60

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: release
    environment:
      name: prod
    if: github.ref_name == 'main' && needs.release.outputs.release_created

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🚢 Deploy
        uses: ./github/actions/deploy
        with:
          web-api-key: ${{ secrets.WEB_API_KEY }}
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          deploy-flags: |
            --concurrency=100
            --cpu=1
            --max-instances=10
            --memory=128Mi
            --min-instances=1
            --timeout=60
